name: password_generator
description: A package to generate strong passwords. Also comes with an extension for
  checking the strength of a password.
version: 1.0.0
publish_to: 'pub.dev'
#repository:
environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
